import urllib.request
from datetime import datetime
import re

SOURCES_FILE = "sources.txt"
OUTPUT_FILE = "Blocklist.txt"
STATS_FILE = "Stats.txt"


def download(url):
    print(f"Downloading: {url}")

    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            return response.read().decode("utf-8", errors="ignore")

    except Exception as e:
        print(f"Failed: {url} -> {e}")
        return ""


def extract_domains(text):
    domains = set()

    for line in text.splitlines():
        line = line.strip()

        if not line:
            continue

        # Ignore comments
        if line.startswith("#") or line.startswith("!"):
            continue

        # Remove inline comments
        line = line.split("#")[0].strip()

        # Hosts format:
        # 0.0.0.0 example.com
        parts = line.split()

        if len(parts) >= 2:
            domain = parts[-1]
        else:
            domain = parts[0]

        # Adblock format:
        # ||example.com^
        if domain.startswith("||"):
            domain = domain[2:]

        # Cleanup
        domain = domain.replace("^", "")
        domain = domain.replace("/", "")
        domain = domain.strip()

        # Skip bad entries
        if "*" in domain:
            continue

        if re.match(r"^[0-9.]+$", domain):
            continue

        if "://" in domain:
            continue

        # Basic domain validation
        if (
            "." in domain
            and " " not in domain
            and len(domain) > 3
        ):
            domains.add(domain.lower())

    return domains


def main():
    all_domains = set()
    source_stats = {}

    with open(SOURCES_FILE, "r") as f:
        sources = [
            x.strip()
            for x in f.readlines()
            if x.strip()
        ]

    for source in sources:
        data = download(source)

        domains = extract_domains(data)

        source_stats[source] = len(domains)

        print(f"{len(domains)} domains found")

        all_domains.update(domains)

    domains = sorted(all_domains)

    header = f"""# Ultimate Pi-hole Blocklist
# Automatically generated by GitHub Actions
#
# Sources: {len(sources)}
# Unique domains: {len(domains)}
# Last updated: {datetime.utcnow()} UTC
#
# Do not edit manually.
#

"""


    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("\n".join(domains))


    with open(STATS_FILE, "w", encoding="utf-8") as f:
        f.write(
f"""# Ultimate Pi-hole Blocklist Statistics

Generated:
{datetime.utcnow()} UTC

Sources:
{len(sources)}

Unique blocked domains:
{len(domains)}

Source breakdown:

"""
        )

        for source, count in source_stats.items():
            f.write(f"- {source}: {count} domains\n")


    print("\n===== SOURCE STATISTICS =====")

    for source, count in source_stats.items():
        print(f"{source}: {count}")

    print("============================")
    print(f"TOTAL UNIQUE DOMAINS: {len(domains)}")


if __name__ == "__main__":
    main()